///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("fa8ed0da-d04a-4461-b8ed-217280a95138", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest4Repository repository.
        /// </summary>
        public static MyTest4Repository repo = MyTest4Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://arukereso.hu' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://arukereso.hu", "Chrome", "", false, true, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArukeresőHuArakEsTermekekOesszeha.InputTagSt' at Center.", repo.ArukeresőHuArakEsTermekekOesszeha.InputTagStInfo, new RecordItemIndex(1));
            repo.ArukeresőHuArakEsTermekekOesszeha.InputTagSt.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'smart watch'.", new RecordItemIndex(2));
            Keyboard.Press("smart watch");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArukeresőHuArakEsTermekekOesszeha.ATagKereses' at Center.", repo.ArukeresőHuArakEsTermekekOesszeha.ATagKeresesInfo, new RecordItemIndex(3));
            repo.ArukeresőHuArakEsTermekekOesszeha.ATagKereses.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArukeresőHuArakEsTermekekOesszeha.SportoraOkosoraKiegeszitő' at Center.", repo.ArukeresőHuArakEsTermekekOesszeha.SportoraOkosoraKiegeszitőInfo, new RecordItemIndex(4));
            repo.ArukeresőHuArakEsTermekekOesszeha.SportoraOkosoraKiegeszitő.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VasarlasSportoraOkosoraKiegeszitőA.OrderDropdown' at Center.", repo.VasarlasSportoraOkosoraKiegeszitőA.OrderDropdownInfo, new RecordItemIndex(5));
            repo.VasarlasSportoraOkosoraKiegeszitőA.OrderDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VasarlasSportoraOkosoraKiegeszitőA.ATagDragak' at Center.", repo.VasarlasSportoraOkosoraKiegeszitőA.ATagDragakInfo, new RecordItemIndex(6));
            repo.VasarlasSportoraOkosoraKiegeszitőA.ATagDragak.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
